# Generated by Django 5.2.7 on 2025-10-25 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('harvest_date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce', to='core.garden')),
            ],
        ),
    ]
