# Generated by Django 5.2.7 on 2025-10-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_garden_latitude_garden_longitude_vendor_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produce',
            name='harvest_date',
        ),
        migrations.RemoveField(
            model_name='produce',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='produce',
            name='price_per_kg',
        ),
        migrations.RemoveField(
            model_name='produce',
            name='quantity_kg',
        ),
        migrations.AddField(
            model_name='garden',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='garden_images/'),
        ),
        migrations.AddField(
            model_name='produce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produce_images/'),
        ),
        migrations.AddField(
            model_name='produce',
            name='quantity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='produce',
            name='unit',
            field=models.CharField(default='kg', max_length=20),
        ),
    ]
