# Generated by Django 5.2.7 on 2025-10-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_produce_harvest_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
