# Generated by Django 5.2.7 on 2025-10-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_garden_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
