# Generated by Django 5.2.7 on 2025-10-25 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_produce_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='produce',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produce')),
            ],
        ),
    ]
