# Generated by Django 5.2.7 on 2025-10-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_garden_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gardens/'),
        ),
    ]
