# Generated by Django 5.2.7 on 2025-10-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_produce_price_alter_produce_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='produce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produce_images/'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
